### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by StruninIhor** [StruninIhor/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Mariia844** [comment]
Привіт, я студент 4 курсу в НТУУ "КПІ" (з недавнього часу - КПІ ім. Ігоря Сікорського). Також я фул-стек розробник. Основний стек, яким користуюсь сьогодні - ASP. NET Core + Angular 8 / 9. Також цікавить програмування плат типу Raspberrypi, Arduino, тощо.
