### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by StruninIhor** [StruninIhor/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Mariia844** [comment]
LinkedIn - https://www.linkedin.com/in/strunin-ihor/
Telegram - https://t.me/strunin_ihor
Email - strunin.ihor@gmail.com
Facebook - https://www.facebook.com/ihor.strunin (Дуже рідко заходжу)

**Comment by StruninIhor** [comment]
І ще гітхаб
