### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by StruninIhor** [StruninIhor/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Mariia844** [comment]
September 2017 - February 2018 - DIXI Center support team
	9 міжнародна виставка "Інноватика в сучаній освіті" + "World Edu" - http://ptmip.ipt.kpi.ua/wp-content/uploads/sites/6/2017/12/Izobrazhenie11.jpg
	Всякі хімічні експерименти із датчиками - https://youtu.be/egnhXmO6yus?t=79
Також треба додати досвід роботи за 2018-2020 роки

**Comment by StruninIhor** [comment]
Інше додам
